require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Napollo' do
  config = use_native_modules!
rn_maps_path = '../node_modules/react-native-maps'
# pod 'react-native-google-maps', :path => rn_maps_path
pod 'Google-Maps-iOS-Utils'
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy"
  
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

  pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"

  pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
  
  pod 'Permission-PhotoLibraryAddOnly', :path => "#{permissions_path}/PhotoLibraryAddOnly"

  target 'NapolloTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
  end
end