export const OPEN_MUSIC_PLAYER = 'OPEN_MUSIC_PLAYER';
export const OPEN_MUSIC_PLAYER_RESET = 'OPEN_MUSIC_PLAYER_RESET';
export const CLOSE_MUSIC_PLAYER = 'CLOSE_MUSIC_PLAYER';
export const OPEN_MUSIC_FROM_MINI_PLAYER = 'OPEN_MUSIC_FROM_MINI_PLAYER';

// GENERAL SONG BOTTOM SHEET
export const OPEN_SONG_BOTTOM_SHEET = 'OPEN_SONG_BOTTOM_SHEET';
export const CLOSE_SONG_BOTTOM_SHEET = 'CLOSE_SONG_BOTTOM_SHEET';
// LISTEN ELSEWHEREMODAL,SINGLE ARTIST MODAL
export const OPEN_LISTEN_SONG_ELSEWHERE_MODAL =
  'OPEN_LISTEN_SONG_ELSEWHERE_MODAL';
export const CLOSE_LISTEN_SONG_ELSEWHERE_MODAL =
  'CLOSE_LISTEN_SONG_ELSEWHERE_MODAL';
// SINGLE ARTIST MODAL
export const OPEN_SINGLE_ARTIST_MODAL = 'OPEN_SINGLE_ARTIST_MODAL';
export const CLOSE_SINGLE_ARTIST_MODAL = 'CLOSE_SINGLE_ARTIST_MODAL';
export const OPEN_SINGLE_LISTENER_MODAL = 'OPEN_SINGLE_LISTENER_MODAL';
export const CLOSE_SINGLE_LISTENER_MODAL = 'CLOSE_SINGLE_LISTENER_MODAL';

//COMMENT REDUCER
export const OPEN_COMMENT_MODAL = 'OPEN_COMMENT_MODAL';
export const CLOSE_COMMENT_MODAL = 'CLOSE_COMMENT_MODAL';
export const OPEN_MEDIA_COMMENT_MODAL = 'OPEN_MEDIA_COMMENT_MODAL';
export const CLOSE_MEDIA_COMMENT_MODAL = 'CLOSE_MEDIA_COMMENT_MODAL';

// GOOGLE_SEARCH_MODAL
export const OPEN_GOOGLE_SEARCH_MODAL = 'OPEN_GOOGLE_SEARCH_MODAL';
export const CLOSE_GOOGLE_SEARCH_MODAL = 'CLOSE_GOOGLE_SEARCH_MODAL';
export const LOCATION_PERMISSION_GRANTED = 'LOCATION_PERMISSION_GRANTED';

// GOOGLE_SEARCH_MODAL
export const OPEN_NOTIFICATION_FILTER_MODAL = 'OPEN_NOTIFICATION_FILTER_MODAL';
export const CLOSE_NOTIFICATION_FILTER_MODAL =
  'CLOSE_NOTIFICATION_FILTER_MODAL';

// USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_LOGOUT = 'USER_LOGIN_LOGOUT';
export const CLEAR_USER_LOGIN_ERROR = 'CLEAR_USER_LOGIN_ERROR';

export const VERIFY_USER_EMAIL_LOADING = 'VERIFY_USER_EMAIL_LOADING';
export const VERIFY_USER_EMAIL_SUCCESS = 'VERIFY_USER_EMAIL_SUCCESS';
export const VERIFY_USER_EMAIL_FAIL = 'VERIFY_USER_EMAIL_FAIL';
export const CLEAR_OTP_STATUSES = 'CLEAR_OTP_STATUSES';
export const CLEAR_OTP_STATUSES_1 = 'CLEAR_OTP_STATUSES_1';
export const CLEAR_OTP_STATUSES_2 = 'CLEAR_OTP_STATUSES_2';
export const CLEAR_OTP_STATUSES_3 = 'CLEAR_OTP_STATUSES_3';
export const VERIFY_USER_PHONE_NUMBER_LOADING =
  'VERIFY_USER_PHONE_NUMBER_LOADING';
export const VERIFY_USER_PHONE_NUMBER_SUCCESS =
  'VERIFY_USER_PHONE_NUMBER_SUCCESS';
export const VERIFY_USER_PHONE_NUMBER_FAIL = 'VERIFY_USER_PHONE_NUMBER_FAIL';

//FORGET PASSWORD
export const GET_FORGET_PASSWORD_OTP_LOADING =
  'GET_FORGET_PASSWORD_OTP_LOADING';
export const GET_FORGET_PASSWORD_OTP_SUCCESS =
  'GET_FORGET_PASSWORD_OTP_SUCCESS';
export const GET_FORGET_PASSWORD_OTP_FAIL = 'GET_FORGET_PASSWORD_OTP_FAIL';
export const CONFIRM_FORGET_PASSWORD_OTP_LOADING =
  'CONFIRM_FORGET_PASSWORD_OTP_LOADING';
export const CONFIRM_FORGET_PASSWORD_OTP_SUCCESS =
  'CONFIRM_FORGET_PASSWORD_OTP_SUCCESS';
export const CONFIRM_FORGET_PASSWORD_OTP_FAIL =
  'CONFIRM_FORGET_PASSWORD_OTP_FAIL';
export const RESET_USER_PASSWORD_LOADING = 'RESET_USER_PASSWORD_LOADING';
export const RESET_USER_PASSWORD_SUCCESS = 'RESET_USER_PASSWORD_SUCCESS';
export const RESET_USER_PASSWORD_FAIL = 'RESET_USER_PASSWORD_FAIL';

export const RESEND_EMAIL_OTP_CODE_LOADING = 'RESEND_EMAIL_OTP_CODE_LOADING';
export const RESEND_EMAIL_OTP_CODE_SUCCESS = 'RESEND_EMAIL_OTP_CODE_SUCCESS';
export const RESEND_EMAIL_OTP_CODE_FAIL = 'RESEND_EMAIL_OTP_CODE_FAIL';
export const RESEND_PHONE_NUMBER_OTP_CODE_LOADING =
  'RESEND_PHONE_NUMBER_OTP_CODE_LOADING';
export const RESEND_PHONE_NUMBER_OTP_CODE_SUCCESS =
  'RESEND_PHONE_NUMBER_OTP_CODE_SUCCESS';
export const RESEND_PHONE_NUMBER_OTP_CODE_FAIL =
  'RESEND_PHONE_NUMBER_OTP_CODE_FAIL';

// GET USER PROFILE
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_WITH_ID_REQUEST = 'USER_PROFILE_WITH_ID_REQUEST';
export const USER_PROFILE_WITH_ID_FAIL = 'USER_PROFILE_WITH_ID_FAIL';
export const USER_PROFILE_WITH_ID_SUCCESS = 'USER_PROFILE_WITH_ID_SUCCESS';
// UPDATE USER PROFILE
export const UPDATE_USER_PROFILE_REQUEST = 'UPDATE_USER_PROFILE_REQUEST';
export const UPDATE_USER_PROFILE_FAIL = 'UPDATE_USER_PROFILE_FAIL';
export const UPDATE_USER_PROFILE_SUCCESS = 'UPDATE_USER_PROFILE_SUCCESS';
export const CLEAR_UPDATE_USER_PROFILE_STATE =
  'CLEAR_UPDATE_ARTIST_PROFILE_STATE';
export const UPDATE_USER_USERNAME_REQUEST = 'UPDATE_USER_USERNAME_REQUEST';
export const UPDATE_USER_USERNAME_FAIL = 'UPDATE_USER_USERNAME_FAIL';
export const UPDATE_USER_USERNAME_SUCCESS = 'UPDATE_USER_USERNAME_SUCCESS';
export const CLEAR_UPDATE_USER_USERNAME_STATE =
  'CLEAR_UPDATE_USER_USERNAME_STATE';
export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST';
export const UPDATE_USER_PASSWORD_FAIL = 'UPDATE_USER_PASSWORD_FAIL';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const CLEAR_UPDATE_USER_PASSWORD_STATE =
  'CLEAR_UPDATE_USER_PASSWORD_STATE';

export const UPGRADE_USER_ACCOUNT_REQUEST = 'UPGRADE_USER_ACCOUNT_REQUEST';
export const UPGRADE_USER_ACCOUNT_SUCCESS = 'UPGRADE_USER_ACCOUNT_SUCCESS';
export const UPGRADE_USER_ACCOUNT_FAIL = 'UPGRADE_USER_ACCOUNT_FAIL';
export const CLEAR_UPGRADE_USER_ACCOUNT_STATE =
  'CLEAR_UPGRADE_USER_ACCOUNT_STATE';

export const UPDATE_USER_PROFILE_PICS_REQUEST =
  'UPDATE_USER_PROFILE_PICS_REQUEST';
export const UPDATE_USER_PROFILE_PICS_FAIL = 'UPDATE_USER_PROFILE_PICS_FAIL';
export const UPDATE_USER_PROFILE_PICS_SUCCESS =
  'UPDATE_USER_PROFILE_PICS_SUCCESS';
// USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const CLEAR_REGISTER_DATA = 'CLEAR_REGISTER_DATA';
export const STORE_USER_REGISTER_DATA = 'STORE_USER_REGISTER_DATA';
export const CLEAR_REGISTER_ERROR = 'CLEAR_REGISTER_ERROR';
export const GET_ACCESS_TOKEN = 'GET_ACCESS_TOKEN';
export const GET_ACCESS_TOKEN_FAIL = 'GET_ACCESS_TOKEN_FAIL';
export const GET_ACCESS_TOKEN_LOADING = 'GET_ACCESS_TOKEN_LOADING';
export const CLEAR_ACCESS_TOKEN = 'CLEAR_ACCESS_TOKEN';
export const CLEAR_USER_PROFILE = 'CLEAR_USER_PROFILE';
export const CLEAR_ARTIST_PROFILE = 'CLEAR_ARTIST_PROFILE';

export const GET_ALL_USERS_LOADING = 'GET_ALL_USERS_LOADING';
export const GET_ALL_USERS_SUCCESS = 'GET_ALL_USERS_SUCCESS';
export const GET_ALL_USERS_FAIL = 'GET_ALL_USERS_FAIL';

//STORE ACTIVE USER DETAIL
export const STORE_ACTIVE_USER_DETAILS = 'STORE_ACTIVE_USER_DETAILS';
export const OPEN_SINGLE_USER_PROFILE_MODAL = 'OPEN_SINGLE_USER_PROFILE_MODAL';
export const CLOSE_SINGLE_USER_PROFILE_MODAL =
  'CLOSE_SINGLE_USER_PROFILE_MODAL';

// ADD TRIM TRACK
export const ADD_TRIM_TRACK_DATA = 'ADD_TRIM_TRACK_DATA';
export const CLEAR_TRIM_TRACK_DATA = 'CLEAR_TRIM_TRACK_DATA';

// USER TYPE
export const CUSTOMER_TYPE = 'CUSTOMER_TYPE';

// APPS GENRE
export const GENRE_LIST_LOADING = 'GENRE_LIST_LOADING';
export const GENRE_LIST_SUCCESS = 'GENRE_LIST_SUCCESS';
export const GENRE_LIST_FAIL = 'GENRE_LIST_FAIL';

// ARTIST REGISTRATION
export const ARTIST_REGISTER_REQUEST = 'ARTIST_REGISTER_REQUEST';
export const ARTIST_REGISTER_FAIL = 'ARTIST_REGISTER_FAIL';
export const ARTIST_REGISTER_SUCCESS = 'ARTIST_REGISTER_SUCCESS';
export const CLEAR_ARTIST_REGISTER_DATA = 'CLEAR_ARTIST_REGISTER_DATA';

//ARTSIST LOGIN
export const ARTIST_LOGIN_REQUEST = 'ARTIST_LOGIN_REQUEST';
export const ARTIST_LOGIN_FAIL = 'ARTIST_LOGIN_FAIL';
export const ARTIST_LOGIN_SUCCESS = 'ARTIST_LOGIN_SUCCESS';
export const ARTIST_LOGIN_LOGOUT = 'ARTIST_LOGIN_LOGOUT';

// GET ARTIST PROFILE
export const ARTIST_PROFILE_REQUEST = 'ARTIST_PROFILE_REQUEST';
export const ARTIST_PROFILE_FAIL = 'ARTIST_PROFILE_FAIL';
export const ARTIST_PROFILE_SUCCESS = 'ARTIST_PROFILE_SUCCESS';

// GET ALL ARTISTS
export const GET_ALL_ARTISTS_LOADING = 'GET_ALL_ARTISTS_LOADING';
export const GET_ALL_ARTISTS_SUCCESS = 'GET_ALL_ARTISTS_SUCCESS';
export const GET_ALL_ARTISTS_FAIL = 'GET_ALL_ARTISTS_FAIL';

//FOLLOW ARTIST
export const FOLLOW_ARTIST_LOADING = 'FOLLOW_ARTIST_LOADING';
export const FOLLOW_ARTIST_FAIL = 'FOLLOW_ARTIST_FAIL';
export const FOLLOW_ARTIST_SUCCESS = 'FOLLOW_ARTIST_SUCCESS';
export const UNFOLLOW_ARTIST_LOADING = 'UNFOLLOW_ARTIST_LOADING';
export const UNFOLLOW_ARTIST_FAIL = 'UNFOLLOW_ARTIST_FAIL';
export const UNFOLLOW_ARTIST_SUCCESS = 'UNFOLLOW_ARTIST_SUCCESS';

// ARTIST SONG POST DETAILS
export const CHOOSE_POST_SONG = 'CHOOSE_POST_SONG';
export const CLEAR_POST_SONG = 'CLEAR_POST_SONG';

//UPDATE ARTIST PROFILE
export const UPDATE_ARTIST_PROFILE_REQUEST = 'UPDATE_ARTIST_PROFILE_REQUEST';
export const UPDATE_ARTIST_PROFILE_FAIL = 'UPDATE_ARTIST_PROFILE_FAIL';
export const UPDATE_ARTIST_PROFILE_SUCCESS = 'UPDATE_ARTIST_PROFILE_SUCCESS';
export const CLEAR_UPDATE_ARTIST_PROFILE_STATE =
  'CLEAR_UPDATE_ARTIST_PROFILE_STATE';

//
export const UPDATE_ARTIST_PROFILE_PICS_REQUEST =
  'UPDATE_ARTIST_PROFILE_PICS_REQUEST';
export const UPDATE_ARTIST_PROFILE_PICS_FAIL =
  'UPDATE_ARTIST_PROFILE_PICS_FAIL';
export const UPDATE_ARTIST_PROFILE_PICS_SUCCESS =
  'UPDATE_ARTIST_PROFILE_PICS_SUCCESS';
export const CLEAR_UPDATE_USER_PROFILE_PICS_STATE =
  'CLEAR_UPDATE_ARTIST_PROFILE_STATE';

//  GET ALL MEDIA
export const GET_MEDIA_LOADING = 'GET_MEDIA_LOADING';
export const GET_MEDIA_SUCCESS = 'GET_MEDIA_SUCCESS';
export const GET_MEDIA_FAIL = 'GET_MEDIA_FAIL';
export const GET_TRAILER_MEDIA_LOADING = 'GET_TRAILER_MEDIA_LOADING';
export const GET_TRAILER_MEDIA_SUCCESS = 'GET_TRAILER_MEDIA_SUCCESS';
export const GET_TRAILER_MEDIA_FAIL = 'GET_TRAILER_MEDIA_FAIL';
export const CLEAR_TRAILER_MEDIA_ERROR = 'CLEAR_TRAILER_MEDIA_ERROR';

export const ADD_MEDIA_TO_DISCOVER_PAGE_LOADING =
  'ADD_MEDIA_TO_DISCOVER_PAGE_LOADING';
export const ADD_MEDIA_TO_DISCOVER_PAGE_SUCCESS =
  'ADD_MEDIA_TO_DISCOVER_PAGE_SUCCESS';
export const ADD_MEDIA_TO_DISCOVER_PAGE_FAIL =
  'ADD_MEDIA_TO_DISCOVER_PAGE_FAIL';

export const GET_USER_DISCOVERED_MEDIA_LOADING =
  'GET_USER_DISCOVERED_MEDIA_LOADING';
export const GET_USER_DISCOVERED_MEDIA_SUCCESS =
  'GET_USER_DISCOVERED_MEDIA_SUCCESS';
export const GET_USER_DISCOVERED_MEDIA_FAIL = 'GET_USER_DISCOVERED_MEDIA_FAIL';

//ARTIST MEDIA
export const GET_ALL_ARTIST_SONGS_LOADING = 'GET_ALL_ARTIST_SONGS_LOADING';
export const GET_ALL_ARTIST_SONGS_SUCCESS = 'GET_ALL_ARTIST_SONGS_SUCCESS';
export const GET_ALL_ARTIST_SONGS_FAIL = 'GET_ALL_ARTIST_SONGS_FAIL';

export const GET_SINGLE_ARTIST_MEDIA_BY_ID_LOADING =
  'GET_SINGLE_ARTIST_MEDIA_BY_ID_LOADING';
export const GET_SINGLE_ARTIST_MEDIA_BY_ID_SUCCESS =
  'GET_SINGLE_ARTIST_MEDIA_BY_ID_SUCCESS';
export const GET_SINGLE_ARTIST_MEDIA_BY_ID_FAIL =
  'GET_SINGLE_ARTIST_MEDIA_BY_ID_FAIL';

export const GET_USER_MEDIA_HISTORY_BY_ID_LOADING =
  'GET_USER_MEDIA_HISTORY_BY_ID_LOADING';
export const GET_USER_MEDIA_HISTORY_BY_ID_SUCCESS =
  'GET_USER_MEDIA_HISTORY_BY_ID_SUCCESS';
export const GET_USER_MEDIA_HISTORY_BY_ID_FAIL =
  'GET_USER_MEDIA_HISTORY_BY_ID_FAIL';

//TRENDING MEDIAS
export const GET_TRENDING_MEDIA_LOADING = 'GET_TRENDING_MEDIA_LOADING';
export const GET_TRENDING_MEDIA_SUCCESS = 'GET_TRENDING_MEDIA_SUCCESS';
export const GET_TRENDING_MEDIA_FAIL = 'GET_TRENDING_MEDIA_FAIL';
export const CLEAR_TRENDING_MEDIA_ERROR = 'CLEAR_TRENDING_MEDIA_ERROR';

export const MARK_SONG_AS_DISCOVERED_LOADING =
  'MARK_SONG_AS_DISCOVERED_LOADING';
export const MARK_SONG_AS_DISCOVERED_SUCCESS =
  'MARK_SONG_AS_DISCOVERED_SUCCESS';
export const MARK_SONG_AS_DISCOVERED_FAIL = 'MARK_SONG_AS_DISCOVERED_FAIL';
// like a discover song
export const LIKE_A_DISCOVER_SONG_LOADING = ' LIKE_A_DISCOVER_SONG_LOADING';
export const LIKE_A_DISCOVER_SONG_SUCCESS = ' LIKE_A_DISCOVER_SONG_SUCCESS';
export const LIKE_A_DISCOVER_SONG_FAIL = ' LIKE_A_DISCOVER_SONG_FAIL';

// GET ALL DISCOVERED SONG
export const GET_ALL_USER_DISCOVERED_SONG_LOADING =
  'GET_ALL_USER_DISCOVERED_SONG_LOADING';
export const GET_ALL_USER_DISCOVERED_SONG_SUCCESS =
  'GET_ALL_USER_DISCOVERED_SONG_SUCCESS';
export const GET_ALL_USER_DISCOVERED_SONG_FAIL =
  'GET_ALL_USER_DISCOVERED_SONG_FAIL';

export const DISCOVER_SCREEN_CURRENT_PAGE = 'DISCOVER_SCREEN_CURRENT_PAGE';
export const RESET_PAGE = 'RESET_PAGE';
export const DISCOVER_SCREEN_CURRENT_SIZE = 'DISCOVER_SCREEN_CURRENT_SIZE';

export const GET_ARTIST_TRENDING_MEDIA_LOADING =
  'GET_ARTIST_TRENDING_MEDIA_LOADING';
export const GET_ARTIST_TRENDING_MEDIA_SUCCESS =
  'GET_ARTIST_TRENDING_MEDIA_SUCCESS';
export const GET_ARTIST_TRENDING_MEDIA_FAIL = 'GET_ARTIST_TRENDING_MEDIA_FAIL';

//ACCOUNTUSER LISTENING HISTORY
export const GET_USER_MEDIA_LISTENING_HISTORY_LOADING =
  'GET_USER_MEDIA_LISTENING_HISTORY_LOADING';
export const GET_USER_MEDIA_LISTENING_HISTORY_SUCCESS =
  'GET_USER_MEDIA_LISTENING_HISTORY_SUCCESS';
export const GET_USER_MEDIA_LISTENING_HISTORY_FAIL =
  'GET_USER_MEDIA_LISTENING_HISTORY_FAIL';

//MEDIA COMMENTS
export const CREATE_MEDIA_COMMENT_LOADING = 'CREATE_MEDIA_COMMENT_LOADING';
export const CREATE_MEDIA_COMMENT_SUCCESS = 'CREATE_MEDIA_COMMENT_SUCCESS';
export const CREATE_MEDIA_COMMENT_FAIL = 'CREATE_MEDIA_COMMENT_FAIL';
export const CREATE_MEDIA_REPLY_LOADING = 'CREATE_MEDIA_REPLY_LOADING';
export const CREATE_MEDIA_REPLY_SUCCESS = 'CREATE_MEDIA_REPLY_SUCCESS';
export const CREATE_MEDIA_REPLY_FAIL = 'CREATE_MEDIA_REPLY_FAIL';
export const GET_MEDIA_COMMENTS_LOADING = 'GET_MEDIA_COMMENTS_LOADING';
export const GET_MEDIA_COMMENTS_SUCCESS = 'GET_MEDIA_COMMENTS_SUCCESS';
export const GET_MEDIA_COMMENTS_FAIL = 'GET_MEDIA_COMMENTS_FAIL';
export const CLEAR_MEDIA_COMMENTS_ERROR = 'CLEAR_MEDIA_COMMENTS_ERROR';

export const GET_MEDIA_COMMENT_DETAILS_LOADING =
  'GET_MEDIA_COMMENT_DETAILS_LOADING';
export const GET_MEDIA_COMMENT_DETAILS_SUCCESS =
  'GET_MEDIA_COMMENT_DETAILS_SUCCESS';
export const GET_MEDIA_COMMENT_DETAILS_FAIL = 'GET_MEDIA_COMMENT_DETAILS_FAIL';
export const DELETE_MEDIA_COMMENT_LOADING = 'DELETE_MEDIA_COMMENT_LOADING';
export const DELETE_MEDIA_COMMENT_SUCCESS = 'DELETE_MEDIA_COMMENT_SUCCESS';
export const DELETE_MEDIA_COMMENT_FAIL = 'DELETE_MEDIA_COMMENT_FAIL';

// PLAYLIST
export const CREATE_PLAYLIST_LOADING = 'CREATE_PLAYLIST_LOADING';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_FAIL = 'CREATE_PLAYLIST_FAIL';
export const CLEAR_PLAYLIST_STATE = 'CLEAR_PLAYLIST_STATE';
export const CREATE_PLAYLIST_FROM_MODAL_LOADING =
  'CREATE_PLAYLIST_FROM_MODAL_LOADING';
export const CREATE_PLAYLIST_FROM_MODAL_SUCCESS =
  'CREATE_PLAYLIST_FROM_MODAL_SUCCESS';
export const CREATE_PLAYLIST_FROM_MODAL_FAIL =
  'CREATE_PLAYLIST_FROM_MODAL_FAIL';
export const CLEAR_PLAYLIST_FROM_MODAL_FORM = 'CLEAR_PLAYLIST_FROM_MODAL_FORM';
export const STORE_ACTIVE_PLAYLIST_DETAILS = 'STORE_ACTIVE_PLAYLIST_DETAILS';
export const CLEAR_PLAYLIST_FORM = 'CLEAR_PLAYLIST_FORM';
export const CLEAR_PLAYLIST_ERROR = 'CLEAR_PLAYLIST_ERROR';
export const UPDATE_PLAYLIST_DETAILS_LOADING =
  'UPDATE_PLAYLIST_DETAILS_LOADING';
export const UPDATE_PLAYLIST_DETAILS_SUCCESS =
  'UPDATE_PLAYLIST_DETAILS_SUCCESS';
export const UPDATE_PLAYLIST_DETAILS_FAIL = 'UPDATE_PLAYLIST_DETAILS_FAIL';
export const CLEAR_UPDATE_PLAYLIST_DETAILS = 'CLEAR_UPDATE_PLAYLIST_DETAILS';
export const DELETE_PLAYLIST_LOADING = 'DELETE_PLAYLIST_LOADING';
export const DELETE_PLAYLIST_SUCCESS = 'DELETE_PLAYLIST_SUCCESS';
export const DELETE_PLAYLIST_FAIL = 'DELETE_PLAYLIST_FAIL';
export const ADD_MEDIA_TO_PLAYLIST_FAIL = 'ADD_MEDIA_TO_PLAYLIST_FAIL';
export const ADD_MEDIA_TO_PLAYLIST_SUCCESS = 'ADD_MEDIA_TO_PLAYLIST_SUCCESS';
export const ADD_MEDIA_TO_PLAYLIST_LOADING = 'ADD_MEDIA_TO_PLAYLIST_LOADING';
export const CLEAR_ADD_MEDIA_TO_PLAYLIST = 'CLEAR_ADD_MEDIA_TO_PLAYLIST';
export const DELETE_MEDIA_FROM_PLAYLIST_FAIL =
  'DELETE_MEDIA_FROM_PLAYLIST_FAIL';
export const DELETE_MEDIA_FROM_PLAYLIST_SUCCESS =
  'DELETE_MEDIA_FROM_PLAYLIST_SUCCESS';
export const DELETE_MEDIA_FROM_PLAYLIST_LOADING =
  'DELETE_MEDIA_FROM_PLAYLIST_LOADING';
export const GET_PLAYLIST_DETAILS_FAIL = 'GET_PLAYLIST_DETAILS_FAIL';
export const GET_PLAYLIST_DETAILS_SUCCESS = 'GET_PLAYLIST_DETAILS_SUCCESS';
export const GET_PLAYLIST_DETAILS_LOADING = 'GET_PLAYLIST_DETAILS_LOADING';
export const GET_ALL_PLAYLIST_FAIL = 'GET_ALL_PLAYLIST_FAIL';
export const GET_ALL_PLAYLIST_SUCCESS = 'GET_ALL_PLAYLIST_SUCCESS';
export const GET_ALL_PLAYLIST_LOADING = 'GET_ALL_PLAYLIST_LOADING';
export const CLEAR_ALL_PLAYLIST_ON_LOGOUT = 'CLEAR_ALL_PLAYLIST_ON_LOGOUT';
export const GET_ALL_USER_PLAYLIST_FAIL = 'GET_ALL_USER_PLAYLIST_FAIL';
export const GET_ALL_USER_PLAYLIST_SUCCESS = 'GET_ALL_USER_PLAYLIST_SUCCESS';
export const CLEAR_ALL_USER_PLAYLIST_ON_LOGOUT =
  'CLEAR_ALL_USER_PLAYLIST_ON_LOGOUT';
export const GET_ALL_USER_PLAYLIST_LOADING = 'GET_ALL_USER_PLAYLIST_LOADING';
export const GET_ALL_MEDIA_IN_PLAYLIST_LOADING =
  'GET_ALL_MEDIA_IN_PLAYLIST_LOADING';
export const GET_ALL_MEDIA_IN_PLAYLIST_SUCCESS =
  'GET_ALL_MEDIA_IN_PLAYLIST_SUCCESS';
export const GET_ALL_MEDIA_IN_PLAYLIST_FAIL = 'GET_ALL_MEDIA_IN_PLAYLIST_FAIL';

//ALBUMS
export const CREATE_ALBUM_LOADING = 'CREATE_ALBUM_LOADING';
export const CREATE_ALBUM_SUCCESS = 'CREATE_ALBUM_SUCCESS';
export const CREATE_ALBUM_FAIL = 'CREATE_ALBUM_FAIL';
export const CLEAR_ALBUM_FORM = 'CLEAR_ALBUM_FORM';
export const CLEAR_ALBUM_ERROR = 'CLEAR_ALBUM_ERROR';
export const CLEAR_ALL_USER_ALBUM_ON_LOGOUT = 'CLEAR_ALL_USER_ALBUM_ON_LOGOUT';
export const STORE_ACTIVE_ALBUM_DETAILS = 'STORE_ACTIVE_ALBUM_DETAILS';

//ALBUM DEATAILS
export const GET_ALBUM_DETAILS_FAIL = 'GET_ALBUM_DETAILS_FAIL';
export const GET_ALBUM_DETAILS_SUCCESS = 'GET_ALBUM_DETAILS_SUCCESS';
export const GET_ALBUM_DETAILS_LOADING = 'GET_ALBUM_DETAILS_LOADING';

export const GET_ALL_USER_ALBUM_FAIL = 'GET_ALL_USER_ALBUM_FAIL';
export const GET_ALL_USER_ALBUM_SUCCESS = 'GET_ALL_USER_ALBUM_SUCCESS';
export const GET_ALL_USER_ALBUM_LOADING = 'GET_ALL_USER_ALBUM_LOADING';
// export const CLEAR_ALL_USER_ALBUM_ON_LOGOUT = 'CLEAR_ALL_USER_ALBUM_ON_LOGOUT';

//DELETE ALBUM
export const DELETE_ALBUM_LOADING = 'DELETE_ALBUM_LOADING';
export const DELETE_ALBUM_SUCCESS = 'DELETE_ALBUM_SUCCESS';
export const DELETE_ALBUM_FAIL = 'DELETE_ALBUM_FAIL';

//UPDATEALBUMS
export const UPDATE_ALBUM_DETAILS_LOADING = 'UPDATE_ALBUM_DETAILS_LOADING';
export const UPDATE_ALBUM_DETAILS_SUCCESS = 'UPDATE_ALBUM_DETAILS_SUCCESS';
export const UPDATE_ALBUM_DETAILS_FAIL = 'UPDATE_ALBUM_DETAILS_FAIL';
export const CLEAR_UPDATE_ALBUM_DETAILS = 'CLEAR_UPDATE_ALBUM_DETAILS';

//PLAYLIST MODALS
export const OPEN_MEDIA_PLAYLIST_MODAL = 'OPEN_MEDIA_PLAYLIST_MODAL';
export const CLOSE_MEDIA_PLAYLIST_MODAL = 'CLOSE_MEDIA_PLAYLIST_MODAL';
export const OPEN_MEDIA_PLAYLIST_MODAL_FORM = 'OPEN_MEDIA_PLAYLIST_MODAL_FORM';
export const CLOSE_MEDIA_PLAYLIST_MODAL_FORM =
  'CLOSE_MEDIA_PLAYLIST_MODAL_FORM';

// UPLOADS
export const MEDIA_UPLOAD_LOADING = 'MEDIA_UPLOAD_LOADING';
export const MEDIA_UPLOAD_SUCCESS = 'MEDIA_UPLOAD_SUCCESS';
export const MEDIA_UPLOAD_FAIL = 'MEDIA_UPLOAD_FAIL';
export const TRIM_MEDIA_UPLOAD_LOADING = 'TRIM_MEDIA_UPLOAD_LOADING';
export const TRIM_MEDIA_UPLOAD_SUCCESS = 'TRIM_MEDIA_UPLOAD_SUCCESS';
export const TRIM_MEDIA_UPLOAD_FAIL = 'TRIM_MEDIA_UPLOAD_FAIL';
export const MEDIA_ART_UPLOAD_LOADING = 'MEDIA_ART_UPLOAD_LOADING';
export const MEDIA_ART_UPLOAD_SUCCESS = 'MEDIA_ART_UPLOAD_SUCCESS';
export const MEDIA_ART_UPLOAD_FAIL = 'MEDIA_ART_UPLOAD_FAIL';

export const MEDIA_UPLOAD_TO_API_LOADING = 'MEDIA_UPLOAD_TO_API_LOADING';
export const MEDIA_UPLOAD_TO_API_SUCCESS = 'MEDIA_UPLOAD_TO_API_SUCCESS';
export const MEDIA_UPLOAD_TO_API_FAIL = 'MEDIA_UPLOAD_TO_API_FAIL';
export const UPLOAD_PROGRESS = 'UPLOAD_PROGRESS';
export const CLEAR_UPLOAD_PROGRESS = 'CLEAR_UPLOAD_PROGRESS';
export const CLEAR_UPLOAD_DATA = 'CLEAR_UPLOAD_DATA';

// MEDIA SEARCH
export const MEDIA_SEARCH_LOADING = 'MEDIA_SEARCH_LOADING';
export const MEDIA_SEARCH_SUCCESS = 'MEDIA_SEARCH_SUCCESS';
export const MEDIA_SEARCH_FAIL = 'MEDIA_SEARCH_FAIL';
export const ARTIST_SEARCH_LOADING = 'ARTIST_SEARCH_LOADING';
export const ARTIST_SEARCH_SUCCESS = 'ARTIST_SEARCH_SUCCESS';
export const ARTIST_SEARCH_FAIL = 'ARTIST_SEARCH_FAIL';
export const ALBUM_SEARCH_LOADING = 'ALBUM_SEARCH_LOADING';
export const ALBUM_SEARCH_SUCCESS = 'ALBUM_SEARCH_SUCCESS';
export const ALBUM_SEARCH_FAIL = 'ALBUM_SEARCH_FAIL';
export const GENRE_SEARCH_LOADING = 'GENRE_SEARCH_LOADING';
export const GENRE_SEARCH_SUCCESS = 'GENRE_SEARCH_SUCCESS';
export const GENRE_SEARCH_FAIL = 'GENRE_SEARCH_FAIL';
export const PLAYLIST_SEARCH_LOADING = 'PLAYLIST_SEARCH_LOADING';
export const PLAYLIST_SEARCH_SUCCESS = 'PLAYLIST_SEARCH_SUCCESS';
export const PLAYLIST_SEARCH_FAIL = 'PLAYLIST_SEARCH_FAIL';

export const SEARCH_SCREEN_MEDIA_LOADING = 'SEARCH_SCREEN_MEDIA_LOADING';
export const SEARCH_SCREEN_MEDIA_SUCCESS = 'SEARCH_SCREEN_MEDIA_SUCCESS';
export const SEARCH_SCREEN_MEDIA_FAIL = 'SEARCH_SCREEN_MEDIA_FAIL';

//USER SEARCH VALUE
export const STORE_USER_SEARCH_VALUE = 'STORE_USER_SEARCH_VALUE';
export const DELETE_USER_SEARCH_VALUE = 'DELETE_USER_SEARCH_VALUE';

//LIKE MEDIA
export const LIKE_MEDIA_lOADING = 'LIKE_MEDIA_lOADING';
export const LIKE_MEDIA_SUCCESS = 'LIKE_MEDIA_SUCCESS';
export const LIKE_MEDIA_FAIL = 'LIKE_MEDIA_FAIL';
//UNLIKE MEDIA
export const UNLIKE_MEDIA_lOADING = 'UNLIKE_MEDIA_lOADING';
export const UNLIKE_MEDIA_SUCCESS = 'UNLIKE_MEDIA_SUCCESS';
export const UNLIKE_MEDIA_FAIL = 'UNLIKE_MEDIA_FAIL';

// SHUFFLE SONGS
export const SHUFFLE_MEDIA_SONGS = 'SHUFFLE_MEDIA_SONGS';
export const UN_SHUFFLE_MEDIA_SONGS = 'UN_SHUFFLE_MEDIA_SONGS';

//STORE USER LOCATION
export const STORE_USER_LOCATION = 'STORE_USER_LOCATION';
export const STORE_USER_COORDINATES = 'STORE_USER_COORDINATES';

// PLAY MEDIA
export const PLAY_MEDIA_LOADING = 'PLAY_MEDIA_LOADING';
export const PLAY_MEDIA_SUCCESS = 'PLAY_MEDIA_SUCCESS';
export const PLAY_MEDIA_FAIL = 'PLAY_MEDIA_FAIL';

//LOGOUT USER WHEN TOKEN EXPIRES
export const LOGOUT_USER_WHEN_TOKEN_EXPIRES = 'LOGOUT_USER_WHEN_TOKEN_EXPIRES';
export const CLEAR_LOGOUT_TOKEN_MESSAGE = 'CLEAR_LOGOUT_TOKEN_MESSAGE';

//STORE USER LIKED MEDIA
export const ADD_MEDIA_TO_LIKED_LIST = 'ADD_MEDIA_TO_LIKED_LIST';
export const REMOVE_MEDIA_FROM_LIKED_LIST = 'REMOVE_MEDIA_FROM_LIKED_LIST';
export const ADD_USER_TO_FOLLOWED_LIST = 'ADD_ARTIST_TO_FOLLOWED_LIST';
export const REMOVE_USER_FROM_FOLLOWED_LIST =
  'REMOVE_ARTIST_FROM_FOLLOWED_LIST';
