const songs = [
  {
    title: 'death bed',
    artist: 'Powfu',
    image: require('./assests/images/death-bed.jpg'),
    id: '1',
    numListening: 2000,
    name: 'Powfu',
    subtitle: 'death bed',
    artwork: 'https://samplesongs.netlify.app/album-arts/death-bed.jpg',
    url: 'https://samplesongs.netlify.app/Death%20Bed.mp3',
    state: 'NY',
    km: 33,
    type: 'rock',
    likes: 0,
    time: '5:21',
    mediaTitle: 'death bed',
    mediaIdentity: '1',
    mediaUrl: 'https://samplesongs.netlify.app/Death%20Bed.mp3',
  },
  {
    title: 'bad liar',
    artist: 'Imagine Dragons',
    image: require('./assests/images/bad-liar.jpg'),
    id: '2',
    numListening: 1200,
    name: 'Imagine Dragons',
    subtitle: 'bad liar',
    artwork: 'https://samplesongs.netlify.app/album-arts/bad-liar.jpg',
    url: 'https://samplesongs.netlify.app/Bad%20Liar.mp3',
    state: 'LA',
    km: 40,
    type: 'R&B',
    likes: 0,
    time: '2:21',
    mediaTitle: 'bad liar',
    mediaIdentity: '2',
    mediaUrl: 'https://samplesongs.netlify.app/Bad%20Liar.mp3',
  },
  {
    title: 'faded',
    artist: 'Alan Walker',
    image: require('./assests/images/faded.jpg'),
    id: '3',
    numListening: 900,
    name: 'Alan Walker',
    subtitle: 'faded',
    artwork: 'https://samplesongs.netlify.app/album-arts/faded.jpg',
    url: 'https://samplesongs.netlify.app/Faded.mp3',
    state: 'MS',
    km: 221,
    type: 'Hip-Hop',
    likes: 0,
    time: '2:22',
    mediaTitle: 'faded',
    mediaIdentity: '3',
    mediaUrl: 'https://samplesongs.netlify.app/Faded.mp3',
  },
  {
    title: 'hate me',
    artist: 'Ellie Goulding',
    image: require('./assests/images/hate-me.jpg'),
    id: '4',
    numListening: 5000,
    name: 'Ellie Goulding',
    subtitle: 'hate me',
    artwork: 'https://samplesongs.netlify.app/album-arts/hate-me.jpg',
    url: 'https://samplesongs.netlify.app/Hate%20Me.mp3',
    state: 'CA',
    km: 400,
    type: 'Afro',
    likes: 0,
    time: '4:05',
    mediaTitle: 'hate me',
    mediaIdentity: '4',
    mediaUrl: 'https://samplesongs.netlify.app/Hate%20Me.mp3',
  },
  {
    title: 'Solo',
    artist: 'Clean Bandit',
    image: require('./assests/images/solo.jpg'),
    id: '5',
    numListening: 1234,
    name: 'Clean Bandit',
    subtitle: 'Solo',
    artwork: 'https://samplesongs.netlify.app/album-arts/solo.jpg',
    url: 'https://samplesongs.netlify.app/Solo.mp3',
    state: 'FA',
    km: 100,
    type: 'Hip-Hop',
    likes: 0,
    time: '3:21',
    mediaTitle: 'Solo',
    mediaIdentity: '5',
    mediaUrl: 'https://samplesongs.netlify.app/Solo.mp3',
  },
  {
    title: 'without me',
    artist: 'Halsey',
    image: require('./assests/images/without-me.jpg'),
    id: '6',
    numListening: 4000,
    name: 'Halsey',
    subtitle: 'without me',
    artwork: 'https://samplesongs.netlify.app/album-arts/without-me.jpg',
    url: 'https://samplesongs.netlify.app/Without%20Me.mp3',
    state: 'MT',
    km: 233,
    type: 'Soul',
    likes: 0,
    time: '5:45',
    mediaTitle: 'without me',
    mediaIdentity: '6',
    mediaUrl: 'https://samplesongs.netlify.app/Without%20Me.mp3',
  },
];

export default songs;
